### ISSUE TITLE
Zoom window record black frame or screen when zoom "Share Screen" running from zoom meeting.

### ISSUE THREAD

**Issue by rakib33** [sskodje/ScreenRecorderLib#201] opened 2022-06-03 10:22 UTC
While recording Zoom meeting  and recorder share the screen from zoom meeting it will take black color frame. the video is ongoing but  black screen.

**Comment by sskodje** [comment] 2022-06-19 20:39
Turns out it was not caused by share screen, but by zoom going fullscreen, which caused a bugged state where no new frames were received. Recording zoom in fullscreen, and presumably other apps doing the same, should be fixed with b53207f83df428b3c5131f849ddfe630ac020def

**Closed by sskodje** 2022-06-19 20:39 UTC

**Comment by rakib33** [comment] 2022-06-23 10:15
Thank you for your kind support and feedback. I test your modification, Its really worked nice. Thank you.
