### ISSUE TITLE
Critical Audio Bug

### ISSUE THREAD

**Issue by ranwer-dev** [sskodje/ScreenRecorderLib#249] opened 2023-05-29 15:00 UTC
With the latest master branch build, audio is getting recorded like cartoonish sound. It was fine when there was **LoopbackCapture** before **WASAPICapture** was added. Sometimes System audio works normally, otherwise it also plays cartoonish.

https://github.com/sskodje/ScreenRecorderLib/assets/92986100/b27e33f6-8e5a-411c-856c-d5c4f36c178a

**Comment by sskodje** [comment] 2023-05-30 09:20
I can't reproduce, so i'm going to need some logs if i'm to look at this.

**Comment by sskodje** [comment] 2023-05-30 13:22
I think i found the error, and pushed a fix with 9b57573.

**Closed as completed** 2023-05-30 13:41 UTC
