### ISSUE TITLE
Does not record anything (No errors either)

### ISSUE THREAD

**Issue by Technerder** [sskodje/ScreenRecorderLib#18] opened 2018-10-21 16:53 UTC
I'm using the current code to try to record my screen, however nothing is being created and no errors are being thrown anywhere.

`using System;
using System.Windows;
using ScreenRecorderLib;

namespace ScreenRecorder {

    public partial class MainWindow : Window {

        private String videoPath;
        private bool shouldRecord;
        private Recorder recorder;

        public MainWindow() {

            InitializeComponent();

            recordButton.Click += OnButtonClick;

            RecorderOptions options = new RecorderOptions {

                RecorderMode = RecorderMode.Video,

                IsThrottlingDisabled = false,
                IsHardwareEncodingEnabled = true,
                IsLowLatencyEnabled = false,
                IsMp4FastStartEnabled = false,

                AudioOptions = new AudioOptions {

                    Bitrate = AudioBitrate.bitrate_128kbps,
                    Channels = AudioChannels.Stereo,
                    IsAudioEnabled = true

                },

                VideoOptions = new VideoOptions {

                    Bitrate = 8000 * 1000,
                    Framerate = 60,
                    IsMousePointerEnabled = true,
                    IsFixedFramerate = true,
                    EncoderProfile = H264Profile.Main

                }

            };

            recorder = Recorder.CreateRecorder(options);
            videoPath = "C:\\Users\\Technerder\\Desktop\\Test.mp4";

        }

        private void OnButtonClick(object sender, RoutedEventArgs e) {

            shouldRecord = !shouldRecord;

            MessageBox.Show("Now: " + (shouldRecord ? "Recording!" : "no longer recording!"));

            if (shouldRecord) {

                recorder.Record(videoPath);

            } else {

                recorder.Stop();

            }

        }

    }

}`

**Comment by sskodje** [comment] 2018-10-21 20:47
I seems i made an error in the last version. It fails if you don't select a monitor to record, when the code is trying to get the default monitor.

The bug is fixed with bb74d6a38b832d04c92b3bbbbd53562db8837a04, and i have updated NuGet with the fix as well.

Thank you for reporting the bug!

**Comment by sskodje** [comment] 2018-10-22 08:37
Does it say 30fps in the properties of the video file generated, or does it just look like it 30 fps? Each frame is only recorded when the screen is reported as updated by Windows. So if you are recording e.g. a Youtube video in 30 fps, naturally the result will also look like 30 fps. This can be best tested by recording a 60 fps video from Youtube for example.

**Comment by Technerder** [comment] 2018-10-22 14:02
I tested by doing that, the video was set to 720p60 however the output video looked like 30 or so fps.

**Comment by sskodje** [comment] 2018-10-22 18:37
It should record in whatever framerate your pc is outputing. If you are unsure, you can download the source and check the debug output. At 60 fps, a frame should be recorded every 16ms give or take a millisecond.

**Comment by Technerder** [comment] 2018-10-26 16:00
I've recorded a few instances but all seem like they've been recorded in 30 fps. Would you be able to test to see if it works on your machine?

**Comment by MJWherry** [comment] 2018-11-06 20:30
Im still getting an issue where i get an error with no feedback on what the issue is...implementing your sr into an automation for unit testing to save a video of a failing test (they are UI unit tests), recording to a memory stream and running a test fails yet pointing to a file path does not...it errors out on _rec.Record(_outStream) where outstream=memorystream

**Comment by sskodje** [comment] 2018-11-06 23:46
Hmm, that's weird. I can't reproduce that issue. Would it be possible for you to post the relevant parts of your code where you create the recorder and stream?

**Closed** 2018-11-07 10:01 UTC
