### ISSUE TITLE
Corrupted file

### ISSUE THREAD

**Issue by aaryamanc** [sskodje/ScreenRecorderLib#28] opened 2019-04-13 16:56 UTC
I've integrated ScreenRecorder with UnitTests in VisualStudio and start recording before every test case and then stops it. On Windows 10 Azure VM (2 Cpus, 16GB RAM), i consistently get Corrupted .mp4 video file after stopping the recording. No error is thrown by ScreenRecorder. 

Is there a way to mitigate this issue?

**Comment by sskodje** [comment] 2019-04-14 22:36
Do the videos get corrupt if you record them on the VM from outside of Visual Studio test case also? Like using the demo app from this project?

**Comment by aaryamanc** [comment] 2019-04-15 05:38
@sskodje :Thank you for looking into it. I tried the same steps in a c# console app on same VM and it works fine. Here is what I've observed:

1. Initially within unit tests i was getting recording error 'Not enough memory available', so i bumped the RAM of VM from 4gb to 16gb and this error went away.

2. Now, i don't see any error but after calling rec.Stop, i don't see the Rec_OnStatusChanged status changed to 'Complete'. It does change to 'Finishing' but not to 'Complete'.

3. What i noticed is that rec.Stop() doesn't stop the recording immediately, hence, Ive to wait until the status is changed to 'Complete'. I added following line after rec.Stop to wait for recording to 'Complete', SpinWait.SpinUntil(() => _isRecordingComplete, 10000). On my physical machine, this check has prevented the corruption totally. But on VM, i'm still seeing corruption as the 'Completed' event is never triggered after 'Finishing.

**Comment by sskodje** [comment] 2019-04-15 16:57
The operation is async. What happens when you press stop is that the recording task stops recording, tells the [Sink Writer](https://docs.microsoft.com/en-us/windows/desktop/medfound/sink-writer) to flush the data and finish the file, clean up resources etc, and when that is done it calls the recording completed callback. This means you need to keep the Recorder instance alive until it finishes, else it gets garbage collected.

The intended behavior when a recording is completed, is for Status to go to "Idle", and either OnRecordingComplete or OnRecordingFailed is called. If neither of those two events are called, my best bet is that your Rercorder instance has gone out of scope and is garbage collected.

This test method is working on both Hyper-v and regular windows 10 for me.

            Stream outStream = new MemoryStream();
            var rec = ScreenRecorderLib.Recorder.CreateRecorder();
            bool isError = false;
            bool isComplete = false;
            ManualResetEvent resetEvent = new ManualResetEvent(false);
            rec.OnRecordingComplete += (s, args) =>
            {
                isComplete = true;
                resetEvent.Set();
            };
            rec.OnRecordingFailed += (s, args) =>
            {
                isError = true;
                resetEvent.Set();
            };

            rec.Record(outStream);
            Thread.Sleep(3000);
            rec.Stop();
            resetEvent.WaitOne(5000);
            Assert.IsNotNull(outStream);
            Assert.IsFalse(isError);
            Assert.IsTrue(isComplete);
            Assert.AreNotEqual(outStream.Length, 0);

**Comment by aaryamanc** [comment] 2019-04-15 18:05
Thanks @sskodje , It's hard to believe that my instance is going out of scope but i'll recheck the code. Is there a way to enable some sort of logging for the library if i've to troubleshoot it further.

**Comment by sskodje** [comment] 2019-04-15 18:54
Unfortunately there is only logging to the debug output, so you need to add the project to your solution directly instead of NuGet, as well as enabling "native code debugging" in your debug configuration.

**Comment by aaryamanc** [comment] 2019-04-15 20:21
Sure, will do that. Thanks once again for all the help. I'll report back my findings.

**Comment by aaryamanc** [comment] 2019-04-16 18:59
@sskodje : I debugged the library and observed that following code is taking roughly 120 secs  to execute in internal_recorder.cpp. With above sample code you shared also i'm able to consistently repro the issue. As long as we wait for the completion event to finish, the video is not corrupted as it is being closed properly. 

				if (!m_TaskWrapperImpl->m_RenderTask.is_done())
					m_TaskWrapperImpl->m_RenderTask.wait();

I put a log before and after these above calls, as shown below, and captured the logs using DebugView : 

				LOG(L"Callig  m_RenderTask.is_done!");				
				if (!m_TaskWrapperImpl->m_RenderTask.is_done())
					m_TaskWrapperImpl->m_RenderTask.wait();				
				LOG(L"Recording completed!");

You can search for these logs in attached file
[ScreenRecorderLogs.LOG](https://github.com/sskodje/ScreenRecorderLib/files/3086454/ScreenRecorderLogs.LOG)

One thing to note: I'm using VS'2019 and x64 build of ScreenRecorderLibrary and have a feeling that this behavior is being caused due to VS'2019. On 2 machines with VS'2017, i'm not seeing this much delay in closing the tasks.

I'm installing VS'2017 on this affected VM and will report back my observation.

**Comment by sskodje** [comment] 2019-04-16 22:45
That's really weird that it's using a full second to write ONE frame of video. In normal circumstances the encoding should be more or less real time, even with weak hardware. Something must be bogging it down, it looks like it is timing out on something for a second every frame, since there is never less then 1 second between them.

It may be a shot in the dark, but is you recording with audio? If so, try turn audio off.

**Comment by aaryamanc** [comment] 2019-04-16 23:17
No, we are not recording with Audio. I think with VS running on that VM, it's getting hammered.

**Closed** 2019-07-30 10:36 UTC
