### ISSUE TITLE
Release build recording failure

### ISSUE THREAD

**Issue by YongbeomBahg** [sskodje/ScreenRecorderLib#76] opened 2020-07-29 08:44 UTC
Hi, My build on Debug mode works well
but Release mode build goes crash with error log from loopback_capture
loopback_capture does pooling sound capture and waits for waiting objects 
and WaitForMultipleObjects returns unexpected value
We expect WAIT_OBJECT_0 or WAIT_OBJECT_0+1 but error log wrote as 
_"Unexpected WaitForMultipleObjects return value **4294967295** on pass 29 after 3487561424 frames"_

**Comment by kmaki565** [comment] 2020-07-30 00:34
@YongbeomBahg - My workaround for this issue is disabling compiler optimization of the library. I'm not sure why, but then Release build works fine.

![image](https://user-images.githubusercontent.com/16055659/88867163-9c98ec00-d247-11ea-9cc4-e5345ddc4433.png)

**Comment by sskodje** [comment] 2020-07-30 02:24
This problem was due to memory corruption that manifested itself only when optimized. It should be fixed with 2.5.0. If not, let me know and i'll reopen the issue.

**Closed by sskodje** 2020-07-30 02:24 UTC

**Comment by kmaki565** [comment] 2020-07-30 05:00
Fix confirmed. Thanks!
