### ISSUE TITLE
Desktop Duplication recording issue for monitors with different GPU

### ISSUE THREAD

**Issue by aqibbanday** [sskodje/ScreenRecorderLib#141] opened 2021-05-19 09:35 UTC
[log.txt](https://github.com/sskodje/ScreenRecorderLib/files/6507536/log.txt)
Log with Trace On.

**Comment by sskodje** [comment] 2021-05-19 10:40
From the documentation, the error is probably one of these:

>E_INVALIDARG for one of the following reasons:

>    The specified device (pDevice) is invalid, was not created on the correct adapter, or was not created from IDXGIFactory1 (or a later version of a DXGI factory interface that inherits from IDXGIFactory1).

>    The calling application is already duplicating this desktop output.

The most likely being that the output is already duplicated, as you can only duplicate the same output once per process.

**Comment by aqibbanday** [comment] 2021-05-19 10:44
![image](https://user-images.githubusercontent.com/10510359/118800086-23918080-b8bd-11eb-944d-f9014a3300a4.png)
It is only happening with desktop duplication and it is happening for a single recording.

**Comment by sskodje** [comment] 2021-05-19 11:03
I'm not able to reproduce it. I'd try installing any pending windows updates and restart the machine, as that can be a source of bugs.

**Comment by aqibbanday** [comment] 2021-05-19 11:05
I installed the latest Windows Update today, Windows 10 21H1. I will also try after restart and update you.

Also,
Can you check this issue: https://github.com/sskodje/ScreenRecorderLib/issues/140

**Comment by aqibbanday** [comment] 2021-05-19 11:49
[log.txt](https://github.com/sskodje/ScreenRecorderLib/files/6508383/log.txt)
Tried restarting, I'm still getting the same issue.
Windows 10 version 19043.985

**Comment by sskodje** [comment] 2021-05-19 13:37
Still not able to reproduce. Does it work for you if you check out an earlier commit?

**Comment by aqibbanday** [comment] 2021-05-19 13:54
It doesn't work anymore.

Now, I am also checking it on a VM.

**Comment by aqibbanday** [comment] 2021-05-19 14:46
Well.
It's happening with my monitor: HP 24f (\\.\DISPLAY4)
For my laptop display its working fine:  (\\.\DISPLAY1)
Note: Display names are as per drop down.
In master branch its working fine.
[hp_display_error_log.txt](https://github.com/sskodje/ScreenRecorderLib/files/6509665/hp_display_error_log.txt)

**Comment by aqibbanday** [comment] 2021-05-19 14:58
Happens with/from: Fixed check for windows.graphics.capture availability

**Comment by aqibbanday** [comment] 2021-05-20 05:07
E_INVALIDARG for one of the following reasons:
The specified device (pDevice) is invalid, was not created on the correct adapter, or was not created from IDXGIFactory1 (or a later version of a DXGI factory interface that inherits from IDXGIFactory1).
The calling application is already duplicating this desktop output.

**Comment by aqibbanday** [comment] 2021-05-20 05:26
FYI I got a new device recently, it  has a dedicated GPU GeForce 3060. The monitor is running on the same.
This issue happened with this device as i started using it yesterday.

**Comment by sskodje** [comment] 2021-05-20 10:15
Hmm i wonder if it's an old bug with Windows where they some times don't play nice when having both a dedicated GPU and an integrated GPU. Do you have a Intel cpu with integrated graphics?

**Comment by aqibbanday** [comment] 2021-05-20 10:18
My laptop display is running on Intel Graphics and is working fine, and external monitor is running on Dedicated GPU and is not working.
Issue is only in multimonitor branch.

**Comment by sskodje** [comment] 2021-05-20 10:21
[This](https://stackoverflow.com/questions/37349427/desktop-duplication-api-switchable-graphics) is the bug i was talking about. I've seen some other people have the same issues in the past.

**Comment by aqibbanday** [comment] 2021-05-20 10:23
> [This](https://stackoverflow.com/questions/37349427/desktop-duplication-api-switchable-graphics) is the bug i was talking about. I've seen some other people have the same issues in the past.

What's confusing me is that its working in master branch.

**Comment by aqibbanday** [comment] 2021-05-20 10:31
You can test it on my device remotely.

**Comment by aqibbanday** [comment] 2021-05-20 10:33
The error we are getting is: E_INVALIDARG not DXGI_ERROR_UNSUPPORTED 

https://docs.microsoft.com/en-us/windows/win32/api/dxgi1_2/nf-dxgi1_2-idxgioutput1-duplicateoutput

**Comment by sskodje** [comment] 2021-05-20 10:38
Hmm yes. I think i see the problem now...

On the main branch, the IDXGIAdapter is passed as a parameter when callint D3D11CreateDevice(). Of course so it knows what adapter to use. But i have forgotten to do that, so it always use default adapter. That's why it does not work with multiple monitors connected to multiple gpus.

I'll push a fix soon.

**Comment by aqibbanday** [comment] 2021-05-20 10:39
You can check it on my PC remotely. We can do it on skype.

**Comment by aqibbanday** [comment] 2021-05-20 10:40
hr = D3D11CreateDevice(
			nullptr,
			DriverTypes[DriverTypeIndex],
			nullptr,
			D3D11_CREATE_DEVICE_BGRA_SUPPORT,
			FeatureLevels,
			ARRAYSIZE(FeatureLevels),
			D3D11_SDK_VERSION,
			&Data->Device,
			&FeatureLevel,
			&Data->Context);
		if (SUCCEEDED(hr))
		{
			// Device creation success, no need to loop anymore
			break;
		}

This is the issue i think?

**Comment by sskodje** [comment] 2021-05-20 10:41
Yes, the first parameter is nullptr, it should be an adapter.

**Comment by aqibbanday** [comment] 2021-05-20 10:42
I was trying to add it there.

**Comment by sskodje** [comment] 2021-05-20 11:18
I'm confident the last commit will fix this issue, if not, let me know.

**Comment by aqibbanday** [comment] 2021-05-20 11:24
Not working.

**Comment by aqibbanday** [comment] 2021-05-20 11:25
[Uploading log.txt…]()

**Comment by aqibbanday** [comment] 2021-05-20 11:49
// Obtain handle to sync shared Surface
		hr = pSource->DxRes.Device->OpenSharedResource(pData->TexSharedHandle, __uuidof(ID3D11Texture2D), reinterpret_cast<void **>(&SharedSurf));
		if (FAILED(hr))
		{
			LOG_ERROR(L"Opening shared texture failed");
			goto Exit;
		}

**Comment by sskodje** [comment] 2021-05-20 12:18
I found an error where i passed __uuidof(IDXGIFactory) instead of __uuidof(IDXGIFactory1) to CreateDXGIFactory1. Perhaps it is related. I'll push the fix.

**Comment by aqibbanday** [comment] 2021-05-20 12:18
Its still not working

**Comment by aqibbanday** [comment] 2021-05-20 12:20
I think it would be better, if you could try and fix it on my PC. What do you say?

**Comment by sskodje** [comment] 2021-05-20 12:22
I'm sorry, i'm not doing remote support. I don't have time for more now anyway. I'll have a look at my laptop later tonight, it has two GPUs.

**Comment by aqibbanday** [comment] 2021-05-20 12:23
> I'm sorry, i'm not doing remote support. I don't have time for more now anyway. I'll have a look at my laptop later tonight, it has two GPUs.

OK, Sure. I thought it would be convenient.

**Comment by sskodje** [comment] 2021-05-20 22:03
How do you mean? The IDXGIAdapter?

**Comment by aqibbanday** [comment] 2021-05-21 02:29
Yes

**Comment by aqibbanday** [comment] 2021-05-21 05:10
> How do you mean? The IDXGIAdapter?

I think, create a device once in a method and then return it wherever it is required. So that all the references have same type of device.
As, i can check the master branch device creation is only happening once.
Same is the case with WindowsGraphicsCapture. So the issue here seems to be with multiple device initialization.

**Comment by aqibbanday** [comment] 2021-05-21 11:16
https://github.com/sskodje/ScreenRecorderLib/issues/141 This commit causes issue with graphics capture also.

**Comment by aqibbanday** [comment] 2021-05-21 11:28
> How do you mean? The IDXGIAdapter?

If i get the Nvidia Adapter it works, but then it doesn't work with the Intel display.

**Comment by sskodje** [comment] 2021-05-23 10:29
This seems to be the solution, but i've not read up on it.

https://docs.microsoft.com/en-us/windows-hardware/drivers/display/using-cross-adapter-resources-in-a-hybrid-system

**Comment by aqibbanday** [comment] 2021-05-23 14:29
When i set the GPU for TestApp to NVIDIA and set the adapter to nullptr for both initializations to get the default adapter. Recording is blank.

**Comment by sskodje** [comment] 2021-05-24 23:07
Should be fixed with b6fc4ff55afed4f62014cbfb3b693a745dae0575. Tested and working with two GPUs.

**Comment by aqibbanday** [comment] 2021-05-25 04:09
> When i set the GPU for TestApp to NVIDIA and set the adapter to nullptr for both CreateDevice initializations to get the default adapter. Recording is blank.

As mentioned here the recording for the monitor running on NVIDIA GPU is Blank and multimonitor is here:
![vlcsnap-2021-05-25-09h36m34s995](https://user-images.githubusercontent.com/10510359/119438082-09ccbf00-bd3d-11eb-9693-29e98217986e.png)

**Comment by aqibbanday** [comment] 2021-05-25 05:20
[blankscreen_log.txt](https://github.com/sskodje/ScreenRecorderLib/files/6536708/blankscreen_log.txt)

**Comment by aqibbanday** [comment] 2021-05-25 06:31
The sample provided by Windows has the same issue when run on NVIDIA GPU.

**Comment by sskodje** [comment] 2021-05-25 09:59
I'm not following completely, did you pull the latest changes? You cannot set all adapters to nullptr, you must record the different physical adapters with their own adapters, then copy the bitmap data over cpu to merge them.

**Comment by aqibbanday** [comment] 2021-05-25 10:01
I have pulled the latest changes. Above is the output, without any changes to the code from my side.

**Comment by aqibbanday** [comment] 2021-05-25 10:02
It doesn't give the error anymore, but the output is like this.

**Comment by aqibbanday** [comment] 2021-06-03 08:26
I think its possible to record with GDI.

**Comment by aqibbanday** [comment] 2021-06-26 14:51
Hey, Did you fix this, I just checked the latest commit, its working fine with DesktopDuplication.

**Comment by sskodje** [comment] 2021-07-06 12:21
Sorry for the late reply, i have been real busy lately. After my limited testing on the machines i have available, it should now work on outputs on different GPUs, with one exception: When using on laptops with Microsoft Hybrid Graphics, the application need to be configured to run on the integrated graphics instead of the discrete graphics. This is a limitation in Desktop Duplication itself, and cannot be worked around to my knowledge.

This simplest workaround is to use Windows Graphics Capture API instead on such machines, which to my knowledge should work on all machines using Windows 10 1803 or higher, so it shuld be well supported.

**Comment by ByteYIFFF** [comment] 2021-08-24 07:43
@aqibbanday To capture the integrated display screen to the independent display screen display, you need cpu to convert the data

**Closed** 2022-01-21 00:48 UTC
