### ISSUE TITLE
App window capture truncated and disturbed when window size is increased

### ISSUE THREAD

**Issue by kmaki565** [sskodje/ScreenRecorderLib#105] opened 2020-11-13 14:03 UTC
Hi @sskodje !
I really praise your excellent work on the new feature of app window recording. It's much more stable than my C# code based on the MSFT sample and somehow produces much smaller size video.
Having said that, as I struggled, it cannot follow window size change very well. When I maximize or get a target window bigger, resulted video will have truncated or purple-colored screen. 
This may be a by-nature issue of window capture and we may not have perfect solution. One idea I can think of is if we detect a (big) change in `contentSize` of frames, then restart a new recording to generate a separate file. Do you have any ideas? 

![Screenshot 2020-11-13 225904](https://user-images.githubusercontent.com/16055659/99079920-ebef0680-2603-11eb-9789-89c0607c3ede.png)

**Comment by sskodje** [comment] 2020-11-13 15:23
I can't reproduce the pink and green problem, but the video will indeed be cropped to the frame size if made larger. I can think of a couple solutions, but none optimal. One could be an option to always record to a frame size the same as the monitor size, that way the window will be recorded with black borders around it if not fullscreen. Another to use a video processor to scale down the image, so if you start recording at  for example 960*540 and then increase window size to 1920x1080, the frame is scaled to 50% to make it fit. The problem here of course, it that the quality will be *drastically* decreased. A third option could perhaps be to record at fullscreen resolution but upsample frames that are smaller. Again, the quality would be poor, especially for text, as you are stretching all frames.

Starting a new recording i think is not feasible. You are of course welcome to fork and do whatever you want with the source, if this is somethig you want to try :)

**Comment by kmaki565** [comment] 2020-11-14 14:28
Thanks for your insights. I agree restarting recording is not practical...
I am trying a workaround in my app (not this library) that maximizes target window (by SendMessage) _before_ starting to record. The UX is not as bad as I thought. I'll see if it works for various scenarios.

**Comment by m6t** [comment] 2021-05-17 12:21
This seems to change the aspect ratio if the window is bigger than the starting resolution in graphics capture mode. Say if we start with 480 width and the window is scaled to 500px with, it is resized to 480px width but the original height stays unchanged so the video becomes skinny. I'm trying to implement aspect ratio preservation rn but my c++ is nearly nonexistent 😅

**Comment by sskodje** [comment] 2022-01-21 00:39
Fixed with 83202d6490ba66d1bba21f0f94e9a7e25449dbe8. Window sources can now be configured with an output size and resize/aspect ratio handling.

**Closed by sskodje** 2022-01-21 00:39 UTC
