### ISSUE TITLE
Flickering video when recording by window handle.

### ISSUE THREAD

**Issue by aadithancsg** [sskodje/ScreenRecorderLib#174] opened 2021-11-17 04:05 UTC
Here is my snapshot of the code

var hwnd = Process.GetCurrentProcess().MainWindowHandle; 
options = new RecorderOptions
{
 DisplayOptions = new DisplayOptions { WindowHandle = hwnd },
RecorderApi = RecorderApi.WindowsGraphicsCapture,  
RecorderMode = RecorderMode.Video
}

I tried most of the settings under video options and options to prevent the flickering but I couldn't. I am able to replicate the same problem in the sample testing apps that comes with the source code. I am not sure what was the problem. Any help will be appreciated.

**Comment by sskodje** [comment] 2021-11-17 22:21
Can you tell me a bit about the system you have problems with? Graphics card, monitor, refresh rate, etc.

**Comment by aadithancsg** [comment] 2021-11-18 14:44
Here is the info 

Monitor : HP EliteDisplay E231 1920*1080
Refresh Rate : 60Hz
Bit Depth: 8bit
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.18363 Build 18363
System SKU	LENOVO_MT_20TR_BU_Think_FM_ThinkPad P15v Gen 1
Processor	Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz, 2304 Mhz, 8 Core(s), 16 Logical Processor(s)
Installed Physical Memory (RAM)	32.0 GB

**Comment by sskodje** [comment] 2021-11-18 15:21
Alright thank you. Is it possible for you to upload a short clip of the flickering here? I'm not able to reproduce this issue myself, so it would be helpful to see what it looks like.

**Comment by aadithancsg** [comment] 2021-11-18 18:11
I have citrix workflow however what i am trying to now is on my local nothing to do with citrix. I cannot record my actual for security reasons however i have create a sample winform app to record where i can see a flickering in the initial part of the video. When i try a microsoft word i am not seeing this issue.. It looks like it depends on what we try to record

https://user-images.githubusercontent.com/67663189/142472635-d0167f70-59f5-4a7a-b195-b9b11bdbf6f1.mp4

.

https://user-images.githubusercontent.com/67663189/142472648-458c9fce-08af-45cb-a770-bf53a9915b10.mp4

.

**Comment by sskodje** [comment] 2021-11-18 22:07
I see what is happening, it's some times writing an empty texture, resulting in black frames. The question is why this happens. Can you check if the same happens on your machine with [this version](https://github.com/sskodje/ScreenRecorderLib/actions/runs/1450922641), which is the latest version on my unreleased work in progress branch.

**Comment by aadithancsg** [comment] 2021-11-18 22:18
Hi, I think something is wrong with the version you gave. When I click on record it creates a folder and media file in my user dir but immediately it shutdown the test app.

**Comment by sskodje** [comment] 2021-11-18 23:33
Yeah, i think i found the issue. You are most likely crashing because you are on an older version of Windows 10 than my machines, and i had added a feature that requires version 2004, but i forgot to check if the api exists.

I pushed a fix, and the new version is [here](https://github.com/sskodje/ScreenRecorderLib/actions/runs/1478803218).

**Comment by aadithancsg** [comment] 2021-11-19 04:07
Hi, It works fine now and I was able to record it successfully on my machine. Can you push your changes to master.

**Comment by sskodje** [comment] 2021-11-22 21:53
It's a part of a larger version update, more or less a complete rewrite, and i'm still finishing off some bugs. I'm aiming for a release before the end of the month.

**Comment by aadithancsg** [comment] 2022-01-06 14:59
Do you have a proposed release date for the newer version?

**Comment by sskodje** [comment] 2022-01-21 00:54
This is now fixed with 83202d6490ba66d1bba21f0f94e9a7e25449dbe8

**Closed by sskodje** 2022-01-21 00:54 UTC

**Comment by aadithancsg** [comment] 2022-01-21 04:22
Thanks for the update. When we record a specific application using MainWindowHandle as mentioned in this thread popups/dialog boxes are not captured. If I record the whole desktop it is working fine. Is this functionality expected?

**Comment by sskodje** [comment] 2022-01-21 13:19
It's a limitation of the API. When you pass a window handle, you only record what the handle owns, and as some things like popup menus are not children of the window you record, they won't be recorded either. I'll open and issue for it and see if there's a way to circumvent the problem.

**Comment by aadithancsg** [comment] 2022-01-21 14:06
I suspected that. Thanks for the explanation.
