### ISSUE TITLE
Recording always fails immediately with "The parameter is incorrect."

### ISSUE THREAD

**Issue by micahmo** [sskodje/ScreenRecorderLib#22] opened 2019-01-18 20:00 UTC
Hi sskodje,

This looks like an awesome library, and I'm very excited to give it a shot and integrate it into my own project!

However, so far I've been unable to use it at all! :-( I've cloned the repository and opened up the solution in Visual Studio. I build the whole solution and run the TestApp project. I leave all of the settings as default and hit Record. Immediately it says "Error: The parameter is incorrect."

I'm not sure if there's any logging I could enable to help you debug this issue, but I don't see anything in the Output window when I run in the debugger.

Thanks for any help you can provide!

![2019-01-18 14_59_58-screenrecorderlib demo](https://user-images.githubusercontent.com/7417301/51410170-d0169880-1b31-11e9-972e-73f165adbe0b.png)

**Comment by paniksystem** [comment] 2019-01-18 20:03
Comment the line:
`RETURN_ON_BAD_HR(SetAttributeU32(encoder, CODECAPI_AVEncAdaptiveMode, eAVEncAdaptiveMode_FrameRate));`
in internal_recorder.cpp

Never got this mode to work.

**Comment by micahmo** [comment] 2019-01-18 20:34
paniksystem, thank you so much for the quick response! That fixed the issue! You are a life saver!

I'll leave the bug open in case sskodje would like to investigate further, but I am all set on my end!

**Comment by sskodje** [comment] 2019-01-19 01:38
I'm glad you got it sorted out. There seems to be a problem with adaptive encoding one some systems. Would you mind sharing what hardware you had this problem on, and if the problem is in both hardware and software encoding?

**Comment by micahmo** [comment] 2019-01-22 14:04
Hi sskodje, thanks for the response!
<br>
> Would you mind sharing what hardware you had this problem on

Here are my basic computer stats. Let me know if you need anything more specific.

![2019-01-22 08_55_08-system](https://user-images.githubusercontent.com/7417301/51540143-b6bc6780-1e23-11e9-99fc-81d737c3cdfe.png)
<br>
> and if the problem is in both hardware and software encoding?

I verified that the problem occurs whether or not I have Hardware Encoding enabled.

Hardware encoding disabled             |  Hardware encoding enabled
:-------------------------:|:-------------------------:
![2019-01-22 09_00_56-screenrecorderlib demo](https://user-images.githubusercontent.com/7417301/51540380-495d0680-1e24-11e9-96d3-82bfdb6f3cee.png)  |  ![2019-01-22 09_00_42-screenrecorderlib demo](https://user-images.githubusercontent.com/7417301/51540386-4d892400-1e24-11e9-8c82-8d4cea35838e.png)

**Comment by sskodje** [comment] 2019-01-23 23:43
This should  be fixed with 14c30040597bdcc4f223175e00475f00c5ea8c20

**Closed by sskodje** 2019-01-23 23:43 UTC

**Comment by micahmo** [comment] 2019-01-24 13:48
I grabbed the latest code and verified that this fix works on my system. Thanks sskodje for being so responsive and taking the time to maintain this library!
