### ISSUE TITLE
Lag or frame drop during window drag

### ISSUE THREAD

**Issue by aqibbanday** [sskodje/ScreenRecorderLib#269] opened 2023-11-22 07:19 UTC
When recording is in progress the app and captured video lags when the window of capture application sample is dragged.

**Comment by sskodje** [comment] 2023-11-30 22:21
Perhaps the machine it happened on was low on system resources? I can't see how dragging a window can affect this library otherwise. Screen recording and video encoding can be demanding on PC.

I'll close this, as i can't reproduce the bug.  If it's reproduceable and happens without any obvious cause, i can reopen it.

**Closed by sskodje** 2023-11-30 22:21 UTC
