### ISSUE TITLE
Recorded video framerate is different from setting framerate.

### ISSUE THREAD

**Issue by ankit4vision** [sskodje/ScreenRecorderLib#187] opened 2022-03-21 13:51 UTC
HI, 
**As per my requirement, I need to record a video with 30fps.** please look at my settings below for RecorderOptions,

![image](https://user-images.githubusercontent.com/25152624/159274550-5ca1e6dd-5a35-4bec-b243-a14f87dfd19b.png)

And in recorded video framerate is diffrent, 

![image](https://user-images.githubusercontent.com/25152624/159274960-3e7b3f6f-a72a-4ebd-b472-495e3ae12c5f.png)

please help me, guys.  **I need a video with 30fps**

**Comment by sskodje** [comment] 2022-03-21 22:53
Hey! I figured out this was due to a misconfiguration of the video encoder in this library, so the constant framerate option is not working as it should. I'll push a fix soon.

**Comment by sskodje** [comment] 2022-03-22 21:37
I pushed a fix, can you confirm the issue is fixed on your end? You can download the sample project for the commit here: https://github.com/sskodje/ScreenRecorderLib/actions/runs/2024932081

**Comment by ankit4vision** [comment] 2022-03-23 13:39
Working fine :) .  Now framerate is constant 30. Thanks for your quick fix! @sskodje

**Closed** 2022-03-23 13:45 UTC
